SELECT e1.ID, e1.NAME AS EMPLOYEE, d.NAME AS DEPARTMENT, e1.SALARY, MAX(e1.SALARY) AS MAXSALARY
FROM department AS d
JOIN employee AS e1 ON e1.DEPARTMENT_ID = d.ID AND e1.SALARY = (
    SELECT MAX(e2.SALARY) FROM employee AS e2
WHERE e2.DEPARTMENT_ID = d.ID)
GROUP BY d.ID
ORDER BY MAXSALARY DESC;