-- CREATE SALARIES DATABASE AND APPLY IT TO BE USED FOR SCRIPTS --
DROP DATABASE IF EXISTS salaries;
CREATE DATABASE salaries DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE salaries;

-- DEPARTMENTS TABLE --
CREATE TABLE DEPARTMENT (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

-- CHIEFS TABLE --
CREATE TABLE CHIEF (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    SALARY INT NOT NULL,
    DEPARTMENT_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

-- EMPLOYEES TABLE --
CREATE TABLE EMPLOYEE (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    SALARY INT NOT NULL,
    DEPARTMENT_ID INT,
    CHIEF_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
    FOREIGN KEY (CHIEF_ID) REFERENCES CHIEF(ID)
);

-- INSERT DATA INTO DEPARTMENTS TABLE --
INSERT INTO DEPARTMENT(ID, NAME) VALUES ('','Production');
INSERT INTO DEPARTMENT(ID, NAME) VALUES ('','Research and Development');
INSERT INTO DEPARTMENT(ID, NAME) VALUES ('','Purchasing');
INSERT INTO DEPARTMENT(ID, NAME) VALUES ('','Marketing');
INSERT INTO DEPARTMENT(ID, NAME) VALUES ('','Human Resource Management');
INSERT INTO DEPARTMENT(ID, NAME) VALUES ('','Accounting and Finance');

-- INSERT DATA INTO CHIEFS TABLE --
INSERT INTO CHIEF(ID, NAME, SALARY, DEPARTMENT_ID) VALUES ('','João Maria',1880,1);
INSERT INTO CHIEF(ID, NAME, SALARY, DEPARTMENT_ID) VALUES ('','Constança Barros',4000,2);
INSERT INTO CHIEF(ID, NAME, SALARY, DEPARTMENT_ID) VALUES ('','Kelly Barbosa',1840,6);

-- INSERT DATA INTO EMPLOYEES TABLE --
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Mara Silva',740,1,1);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Daniel Mota',1880,1,1);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Tiago Alcântara',2450,1,1);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Henrique Alves',950,1,1);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Carolina Gonçalves',3000,1,1);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Manuel Paiva',3584,2,2);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Joaquim Nogueira',3566,2,2);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Lara Monteiro',3660,3,NULL);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Beatriz Jardim',2050,3,NULL);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Filomena Aguiar',1316,4,NULL);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Clotilde Almeida',2160,4,NULL);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Luís Inácio',4890,4,NULL);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Verónica Medeiros',5781,5,NULL);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Marta Linhares',3320,5,NULL);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Carlos Branco',1710,6,3);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Olga Madruga',2420,6,3);
INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT_ID, CHIEF_ID) VALUES ('','Joana Dâmaso',2510,6,3);