SELECT d.ID, d.NAME AS DEPARTMENT, COUNT(e.DEPARTMENT_ID) AS TOTAL
FROM department AS d JOIN employee AS e ON d.ID = e.DEPARTMENT_ID
GROUP BY d.NAME HAVING COUNT(e.DEPARTMENT_ID) <= 3
ORDER BY COUNT(e.DEPARTMENT_ID) DESC;